# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstagramProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstagramProject
  pod 'Alamofire', '~> 4.7'
  pod 'Kingfisher', '~> 4.8'
  pod 'SnapKit', '~> 4.0'
  pod 'ObjectMapper', '~> 3.3'
  pod 'CGFloatLiteral', '~> 0.4'
  pod 'Then', '~> 2.3'
  pod 'ManualLayout', '~> 1.3'

end
